### ISSUE TITLE
QUser, QRelationship, QMicropost classes not found during compilation

### ISSUE THREAD

**Issue by alfishe** [springboot-angular2-tutorial/boot-app#1]
Seems enhanced classes were developed to replace regular ones but never added to the repo
Commit 4f35f71b32c96b9afd2d697b03d32ec8e73c70fd (Jan-29) was the last compilable. All further refactorings are broken then

**Comment by akirasosa** [comment]
@alfishe 
They will be automatically generated by annotation processor. If they were not generated, please try following.

```
mvn clean compile
```

Thanks,

**Comment by akirasosa** [comment]
@alfishe 
I confirmed that it happens in importing new project in Intellij IDEA.
![micropostrepositoryimpl_java_-_springboot-angular2-tutorial_-____desktop_boot-app__-_intellij_idea__minerva__iu-144_4199_23](https://cloud.githubusercontent.com/assets/1509852/13415184/65f68c6a-df8b-11e5-9275-de53b932924e.jpg)

I'm afraid that it is a problem of IDEA. But here is a work around.
1. Do `mvn clean compile`
2. Comment out some lines (line 184~206 was OK) on pom.xml and import changes
3. Revert the pom.xml and import changes.

After that generated sources under `target/generated-sources` would be recognised by IDEA.
