### ISSUE TITLE
Project isn't compile

### ISSUE THREAD

**Issue by esuv** [springboot-angular2-tutorial/boot-app#12]
Thank you for sharing tutorial!
Unfortunately, isn't compile
Please, fix it

```
import com.myapp.domain.QRelationship;
import com.myapp.domain.QUser;
```
missing classes...

**Comment by akirasosa** [comment]
@EvgeniySuvorov 
Thanks for trying this repo. Could you try following?
https://github.com/springboot-angular2-tutorial/boot-app#important-note

**Comment by esuv** [comment]
I suppose your tutorial too much complex for beginners...
I expect to see and learn [Demo](https://micropost.hana053.com/) application based on Spring Boot & Angular 2, but I can't find even html pages...
Sorry for my English.

**Comment by akirasosa** [comment]
@EvgeniySuvorov 
> but I can't find even html pages

Sorry about it. I migrated infrastructure yesterday. I got weird problem then, and it was down for a while... It's up now. Take a look if you have time.

I hope this project helps you someday. Thanks,
