### ISSUE TITLE
Build project in Eclipse IDE

### ISSUE THREAD

**Issue by yhrchan** [springboot-angular2-tutorial/boot-app#8]
Hi, just wondering if this project could be built within the Eclipse IDE since I was trying to but got errors.

Thanks!

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building springboot-angular2-tutorial 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ springboot-angular2-tutorial ---
[INFO] Deleting D:\Development\Projects\boot-app\target
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ springboot-angular2-tutorial ---
[INFO] Source directory: D:\Development\Projects\boot-app\src-gen\main\java added.
[INFO] Source directory: D:\Development\Projects\boot-app\target\generated-sources\java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ springboot-angular2-tutorial ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ springboot-angular2-tutorial ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 41 source files to D:\Development\Projects\boot-app\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error reading C:\Users\Ricky.m2\repository\ch\qos\logback\logback-classic\1.1.7\logback-classic-1.1.7.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Ricky.m2\repository\org\springframework\boot\spring-boot\1.4.1.RELEASE\spring-boot-1.4.1.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Ricky.m2\repository\org\springframework\boot\spring-boot-autoconfigure\1.4.1.RELEASE\spring-boot-autoconfigure-1.4.1.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[3,24] cannot find symbol
  symbol:   class QRelationship
  location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[4,24] cannot find symbol
  symbol:   class QUser
  location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[25,19] cannot find symbol
  symbol:   class QUser
  location: class com.myapp.repository.UserRepositoryImpl
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[26,19] cannot find symbol
  symbol:   class QRelationship
  location: class com.myapp.repository.UserRepositoryImpl
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[3,24] cannot find symbol
  symbol:   class QMicropost
  location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[4,24] cannot find symbol
  symbol:   class QRelationship
  location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[5,24] cannot find symbol
  symbol:   class QUser
  location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[17,72] cannot find symbol
  symbol:   class QUser
  location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[26,59] cannot find symbol
  symbol:   class QUser
  location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[38,54] cannot find symbol
  symbol:   class QUser
  location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[45,55] cannot find symbol
  symbol:   class QUser
  location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[52,50] cannot find symbol
  symbol:   class QUser
  location: class com.myapp.repository.helper.UserStatsQueryHelper
[INFO] 15 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.983 s
[INFO] Finished at: 2016-10-26T00:45:19-06:00
[INFO] Final Memory: 24M/57M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project springboot-angular2-tutorial: Compilation failure: Compilation failure:
[ERROR] error reading C:\Users\Ricky.m2\repository\ch\qos\logback\logback-classic\1.1.7\logback-classic-1.1.7.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Ricky.m2\repository\org\springframework\boot\spring-boot\1.4.1.RELEASE\spring-boot-1.4.1.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] error reading C:\Users\Ricky.m2\repository\org\springframework\boot\spring-boot-autoconfigure\1.4.1.RELEASE\spring-boot-autoconfigure-1.4.1.RELEASE.jar; invalid LOC header (bad signature)
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[3,24] cannot find symbol
[ERROR] symbol:   class QRelationship
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[4,24] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[25,19] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.UserRepositoryImpl
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[26,19] cannot find symbol
[ERROR] symbol:   class QRelationship
[ERROR] location: class com.myapp.repository.UserRepositoryImpl
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[3,24] cannot find symbol
[ERROR] symbol:   class QMicropost
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[4,24] cannot find symbol
[ERROR] symbol:   class QRelationship
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[5,24] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[17,72] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[26,59] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[38,54] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[45,55] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[52,50] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by akirasosa** [comment]
@yhrchan 
It looks that generated code by annotation processor were not recognised well. Could you try following?
https://github.com/springboot-angular2-tutorial/boot-app#important-note

I have not tried Eclipse, but maybe it can fix it as same.

**Comment by yhrchan** [comment]
Hi,

I tried that and it gives me the following errors:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.028 s
[INFO] Finished at: 2016-11-02T10:35:18-06:00
[INFO] Final Memory: 29M/214M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project springboot-angular2-tutorial: Compilation failure: Compilation failure:
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[3,24] cannot find symbol
[ERROR] symbol:   class QRelationship
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[4,24] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[25,19] cannot find symbol [ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.UserRepositoryImpl
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/UserRepositoryImpl.java:[26,19] cannot find symbol [ERROR] symbol:   class QRelationship
[ERROR] location: class com.myapp.repository.UserRepositoryImpl
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/auth/SecurityConfig.java:[5,44] cannot find symbol
[ERROR] symbol:   class FilterRegistrationBean
[ERROR] location: package org.springframework.boot.web.servlet
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/auth/SecurityConfig.java:[71,12] cannot find symbol
[ERROR] symbol:   class FilterRegistrationBean
[ERROR] location: class com.myapp.auth.SecurityConfig
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[3,24] cannot find symbol
[ERROR] symbol:   class QMicropost
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[4,24] cannot find symbol
[ERROR] symbol:   class QRelationship
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[5,24] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: package com.myapp.domain
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[17,72] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[26,59] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[38,54] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[45,55] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] /D:/Development/Projects/boot-app/src/main/java/com/myapp/repository/helper/UserStatsQueryHelper.java:[52,50] cannot find symbol
[ERROR] symbol:   class QUser
[ERROR] location: class com.myapp.repository.helper.UserStatsQueryHelper
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Thanks,

Ricky

**Comment by akirasosa** [comment]
Does this link help you?

http://stackoverflow.com/questions/24482259/eclipse-issue-with-maven-build-and-jdk-when-generating-qclasses-in-querydsl
